#!/usr/bin/env python

import bottle
from showboat.util import *
from mako.template import Template
import argparse

# parse commandline args
parser = argparse.ArgumentParser(description='Serve a showboat presentation')
parser.add_argument('src_path', default='.',
                    help='the project path')
parser.add_argument('--host', default='localhost')
parser.add_argument('--port', default=8080, type=int)

args = parser.parse_args()

app = bottle.Bottle()

# TODO: routes for launching editing applications on the "server"-side
# wouldn't it be neat if there were an "edit" option that could locally launch 
# whatever external editor I like?
@app.route('/edit/<path:path>')
def edit(path):
    cmd = Template(config['editor_cmd']).render(path=path)
    syscall(cmd)


@app.route('/<path:path>')
def static_route(path):
    return bottle.static_file(path, args.src_path)

bottle.run(app, host=args.host, port=args.port, quiet=True)
