#!/usr/bin/env python

import bottle
from showboat.util import launch_external_svg_editor, save_svg_file
from mako.template import Template
import argparse


# parse commandline args
parser = argparse.ArgumentParser(description='Serve a showboat presentation')
parser.add_argument('src_path', default='.',
                    help='the project path')
parser.add_argument('--host', default='localhost')
parser.add_argument('--port', default=8080, type=int)

args = parser.parse_args()

app = bottle.Bottle()

# TODO: routes for launching editing applications on the "server"-side
# wouldn't it be neat if there were an "edit" option that could locally launch 
# whatever external editor I like?
@app.route('/edit/svg/<file_path:path>')
def edit(file_path):
    launch_external_svg_editor(file_path)

@app.post('/save/svg/<path:path>')
def save(path):
    data = bottle.request.forms.data
    save_svg_file(path, data)

    print("Saved to {%s}" % path)
    return "OK"

@app.route('/<path:path>')
def static_route(path):
    return bottle.static_file(path, args.src_path)
    


bottle.run(app, host=args.host, port=args.port, quiet=True, server='cherrypy')
