#!/usr/bin/env python

import argparse
import os
import shutil
import shlex
import subprocess
import re
import time

from showboat import compile, deposit_skeleton, view_url, present_url, serve_http


parser = argparse.ArgumentParser(description='Compile a showboat presentation')
parser.add_argument('command', type=str,
                    help='the command for showboat to perform')
parser.add_argument('src_path', default='.',
                    help='the project path')
parser.add_argument('--copy_assets', action='store_true', default=False)
parser.add_argument('--out_path', '-o', default='./output')

args = parser.parse_args()



index_path = os.path.abspath(os.path.expanduser(os.path.join(args.out_path, 
                                                'output', 
                                                'index.html')))

if args.command == 'start':
    deposit_skeleton(args.src_path)
elif args.command == 'compile':
    compile(args.src_path, args.out_path, copy_assets=args.copy_assets)
elif args.command == 'view':
    compile(args.src_path, args.out_path, copy_assets=args.copy_assets)
    view_url(index_path)
elif args.command == 'present':
    compile(args.src_path, args.out_path, copy_assets=args.copy_assets)
    present_url(index_path)
elif args.command == 'serve':
    
    src_path = args.src_path
    if not os.path.exists(os.path.join(src_path, 'index.html')):
        src_path = os.path.join(src_path, 'output')
    
    http_server = serve_http(src_path)
    print("HTTP Server launched on http://localhost:8080.html. Press Ctl-C to quit.")

    view_url('http://localhost:8080/index.html')

    
    try:
        while True:
            time.sleep(1.0)
    except KeyboardInterrupt:
        print('Quitting...')
        http_server.kill()
        
else:
    raise Exception('Unknown command: %s' % args.command)
